/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedNewSessionRouteImport } from './routes/_authed/new-session'
import { Route as AuthedInterviewRouteImport } from './routes/_authed/interview'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedNewSessionRoute = AuthedNewSessionRouteImport.update({
  id: '/new-session',
  path: '/new-session',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedInterviewRoute = AuthedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/interview': typeof AuthedInterviewRoute
  '/new-session': typeof AuthedNewSessionRoute
  '/reports': typeof AuthedReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/interview': typeof AuthedInterviewRoute
  '/new-session': typeof AuthedNewSessionRoute
  '/reports': typeof AuthedReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/interview': typeof AuthedInterviewRoute
  '/_authed/new-session': typeof AuthedNewSessionRoute
  '/_authed/reports': typeof AuthedReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sso-callback'
    | '/dashboard'
    | '/interview'
    | '/new-session'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sso-callback'
    | '/dashboard'
    | '/interview'
    | '/new-session'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/sso-callback'
    | '/_authed/dashboard'
    | '/_authed/interview'
    | '/_authed/new-session'
    | '/_authed/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/new-session': {
      id: '/_authed/new-session'
      path: '/new-session'
      fullPath: '/new-session'
      preLoaderRoute: typeof AuthedNewSessionRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/interview': {
      id: '/_authed/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthedInterviewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedInterviewRoute: typeof AuthedInterviewRoute
  AuthedNewSessionRoute: typeof AuthedNewSessionRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedInterviewRoute: AuthedInterviewRoute,
  AuthedNewSessionRoute: AuthedNewSessionRoute,
  AuthedReportsRoute: AuthedReportsRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SsoCallbackRoute: SsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
