/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedCreditsRouteImport } from './routes/_authed/credits'
import { Route as AuthedInterviewIndexRouteImport } from './routes/_authed/interview/index'
import { Route as AuthedInterviewSetupRouteImport } from './routes/_authed/interview/setup'
import { Route as AuthedInterviewReportsRouteImport } from './routes/_authed/interview/reports'
import { Route as AuthedInterviewSessionSessionIdRouteImport } from './routes/_authed/interview/session/$sessionId'
import { Route as AuthedInterviewReportSessionIdRouteImport } from './routes/_authed/interview/report/$sessionId'
import { Route as AuthedInterviewAnalysisSessionIdRouteImport } from './routes/_authed/interview/analysis/$sessionId'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCreditsRoute = AuthedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedInterviewIndexRoute = AuthedInterviewIndexRouteImport.update({
  id: '/interview/',
  path: '/interview/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedInterviewSetupRoute = AuthedInterviewSetupRouteImport.update({
  id: '/interview/setup',
  path: '/interview/setup',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedInterviewReportsRoute = AuthedInterviewReportsRouteImport.update({
  id: '/interview/reports',
  path: '/interview/reports',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedInterviewSessionSessionIdRoute =
  AuthedInterviewSessionSessionIdRouteImport.update({
    id: '/interview/session/$sessionId',
    path: '/interview/session/$sessionId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedInterviewReportSessionIdRoute =
  AuthedInterviewReportSessionIdRouteImport.update({
    id: '/interview/report/$sessionId',
    path: '/interview/report/$sessionId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedInterviewAnalysisSessionIdRoute =
  AuthedInterviewAnalysisSessionIdRouteImport.update({
    id: '/interview/analysis/$sessionId',
    path: '/interview/analysis/$sessionId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/credits': typeof AuthedCreditsRoute
  '/interview/reports': typeof AuthedInterviewReportsRoute
  '/interview/setup': typeof AuthedInterviewSetupRoute
  '/interview': typeof AuthedInterviewIndexRoute
  '/interview/analysis/$sessionId': typeof AuthedInterviewAnalysisSessionIdRoute
  '/interview/report/$sessionId': typeof AuthedInterviewReportSessionIdRoute
  '/interview/session/$sessionId': typeof AuthedInterviewSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/credits': typeof AuthedCreditsRoute
  '/interview/reports': typeof AuthedInterviewReportsRoute
  '/interview/setup': typeof AuthedInterviewSetupRoute
  '/interview': typeof AuthedInterviewIndexRoute
  '/interview/analysis/$sessionId': typeof AuthedInterviewAnalysisSessionIdRoute
  '/interview/report/$sessionId': typeof AuthedInterviewReportSessionIdRoute
  '/interview/session/$sessionId': typeof AuthedInterviewSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_authed/credits': typeof AuthedCreditsRoute
  '/_authed/interview/reports': typeof AuthedInterviewReportsRoute
  '/_authed/interview/setup': typeof AuthedInterviewSetupRoute
  '/_authed/interview/': typeof AuthedInterviewIndexRoute
  '/_authed/interview/analysis/$sessionId': typeof AuthedInterviewAnalysisSessionIdRoute
  '/_authed/interview/report/$sessionId': typeof AuthedInterviewReportSessionIdRoute
  '/_authed/interview/session/$sessionId': typeof AuthedInterviewSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sso-callback'
    | '/credits'
    | '/interview/reports'
    | '/interview/setup'
    | '/interview'
    | '/interview/analysis/$sessionId'
    | '/interview/report/$sessionId'
    | '/interview/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sso-callback'
    | '/credits'
    | '/interview/reports'
    | '/interview/setup'
    | '/interview'
    | '/interview/analysis/$sessionId'
    | '/interview/report/$sessionId'
    | '/interview/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/sso-callback'
    | '/_authed/credits'
    | '/_authed/interview/reports'
    | '/_authed/interview/setup'
    | '/_authed/interview/'
    | '/_authed/interview/analysis/$sessionId'
    | '/_authed/interview/report/$sessionId'
    | '/_authed/interview/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/credits': {
      id: '/_authed/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthedCreditsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/interview/': {
      id: '/_authed/interview/'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthedInterviewIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/interview/setup': {
      id: '/_authed/interview/setup'
      path: '/interview/setup'
      fullPath: '/interview/setup'
      preLoaderRoute: typeof AuthedInterviewSetupRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/interview/reports': {
      id: '/_authed/interview/reports'
      path: '/interview/reports'
      fullPath: '/interview/reports'
      preLoaderRoute: typeof AuthedInterviewReportsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/interview/session/$sessionId': {
      id: '/_authed/interview/session/$sessionId'
      path: '/interview/session/$sessionId'
      fullPath: '/interview/session/$sessionId'
      preLoaderRoute: typeof AuthedInterviewSessionSessionIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/interview/report/$sessionId': {
      id: '/_authed/interview/report/$sessionId'
      path: '/interview/report/$sessionId'
      fullPath: '/interview/report/$sessionId'
      preLoaderRoute: typeof AuthedInterviewReportSessionIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/interview/analysis/$sessionId': {
      id: '/_authed/interview/analysis/$sessionId'
      path: '/interview/analysis/$sessionId'
      fullPath: '/interview/analysis/$sessionId'
      preLoaderRoute: typeof AuthedInterviewAnalysisSessionIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedCreditsRoute: typeof AuthedCreditsRoute
  AuthedInterviewReportsRoute: typeof AuthedInterviewReportsRoute
  AuthedInterviewSetupRoute: typeof AuthedInterviewSetupRoute
  AuthedInterviewIndexRoute: typeof AuthedInterviewIndexRoute
  AuthedInterviewAnalysisSessionIdRoute: typeof AuthedInterviewAnalysisSessionIdRoute
  AuthedInterviewReportSessionIdRoute: typeof AuthedInterviewReportSessionIdRoute
  AuthedInterviewSessionSessionIdRoute: typeof AuthedInterviewSessionSessionIdRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedCreditsRoute: AuthedCreditsRoute,
  AuthedInterviewReportsRoute: AuthedInterviewReportsRoute,
  AuthedInterviewSetupRoute: AuthedInterviewSetupRoute,
  AuthedInterviewIndexRoute: AuthedInterviewIndexRoute,
  AuthedInterviewAnalysisSessionIdRoute: AuthedInterviewAnalysisSessionIdRoute,
  AuthedInterviewReportSessionIdRoute: AuthedInterviewReportSessionIdRoute,
  AuthedInterviewSessionSessionIdRoute: AuthedInterviewSessionSessionIdRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SsoCallbackRoute: SsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
